name: Java CI Build and Test

# This workflow runs on pushes or pull requests to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # A popular, free OpenJDK distribution
          cache: 'maven' # Caches Maven dependencies for faster builds

      # Step 3: Run the tests with Maven
      - name: Run Maven Tests
        run: mvn -B test --file pom.xml